### ISSUE TITLE
Youtube UserStyle not working

### ISSUE THREAD

**Issue by Infamous-Ironman** [catppuccin/userstyles#169] opened 2023-08-13 09:23 UTC
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

There is a CSS Syntax error causing Userstyle not to work

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/128158627/d02a2a5c-e1c5-492e-9c3a-07b4f803ede6)
![image](https://github.com/catppuccin/userstyles/assets/128158627/3baf9f86-f014-4ee1-84e7-324fca06a8bd)

### What browser(s) are you seeing the problem on?

Firefox v112.0.2

**Comment by isabelroses** [comment] 2023-08-13 09:27
The unknown word should not be the cause, it gets that error as it sees catppuccin as a spelling error.
And if you notice the accent has applied to the channel names. Seeing the location of where the error occurred this could be a duplicate of #167

**Closed** 2023-08-13 12:22 UTC
Labels: youtube
