### ISSUE TITLE
containers (tweet / timeline tabs, etc) still use default twitter bg colors

### ISSUE THREAD

**Issue by foreigndistance** [catppuccin/userstyles#932] opened 2024-05-31 11:44 UTC
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:twitter

### Describe your problem.
The background for these specific containers (shown in these screenshots) still use the default Twitter colors, and doesn't use the Catppuccin colors at all.

### Attach screenshots.
![Screenshot 2024-05-31 at 19-33-06 Home _ Twitter](https://github.com/catppuccin/userstyles/assets/108866972/a4e1cbbc-e55e-4935-a4c0-256cb7e92a8d)
![Screenshot 2024-05-31 at 19-33-57 Home _ X](https://github.com/catppuccin/userstyles/assets/108866972/ecc003c2-2746-4c1a-a051-aa931c4ffdf1)
![Screenshot 2024-05-31 at 19-40-18 Home _ Twitter](https://github.com/catppuccin/userstyles/assets/108866972/93dadb76-72c0-41e3-922b-5ae33bc8add6)
![image](https://github.com/catppuccin/userstyles/assets/108866972/688c7759-be21-45b8-ad73-c3434639c1a5)

### What browser(s) are you seeing the problem on?

Firefox Developer Edition v127.0b8 (64-bit)

**Comment by uncenter** [comment] 2024-05-31 11:45
![Screenshot 2024-05-31 at 07 45 21 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/dd43cc0a-247e-433b-9b72-228b7281021d)

Hmm I can't reproduce? Might be an A/B testing update to it though.

**Comment by uncenter** [comment] 2024-05-31 11:46
Ah, I see that your "Post" button still says "Tweet". What extensions are you using? Can you try disabling them?

**Comment by foreigndistance** [comment] 2024-05-31 11:50
The only other extension I have enabled for this site is Control Panel for Twitter. Disabling it also shows the issues present in the Trending, Who to Follow, and Message tabs.
(I forgot to include that in the original issue since I don't use the site's right side tbh)
![image](https://github.com/catppuccin/userstyles/assets/108866972/eec91e63-b743-435a-a899-27517db41dc9)

**Comment by foreigndistance** [comment] 2024-05-31 11:52
For now I've edited the issue post.

**Comment by uncenter** [comment] 2024-06-06 13:35
I'm unable to reproduce this. Are you still seeing this?

**Comment by uncenter** [comment] 2024-06-08 15:12
I'm going to close this for now. If this is still an issue and anyone else can reproduce I'll reopen.

**Closed by uncenter** 2024-06-08 15:12 UTC
Labels: twitter, difficult/unable to repro

**Comment by isabelroses** [comment] 2024-06-08 15:15
Change from "dim" to "lights out", hat fixes this. :p

![image](https://github.com/catppuccin/userstyles/assets/71222764/4fef56b9-a1f1-45c6-82b1-1342e1fe3224)

**Comment by uncenter** [comment] 2024-06-08 15:16
Which is suggested by our usage note: https://github.com/catppuccin/userstyles/tree/main/styles/twitter#usage :)
